[project]
name = "ptt-bridge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gpiozero>=2.0.1",
    "ruff>=0.11.5",
    "sox>=1.5.0",
]
